apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  type: NodePort
  selector:
    app: api-deployment
  ports:
  - port: 8000
    protocol: TCP
    targetPort: api-port
